language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-28.0.3
  - android-26
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
env:
  global:
  - secure: f1onxrp8MHHFQQtf0zXV+pibitILtiEqp7sDN5/EPyIDk8B6RBQrhTXV97/6OToNgr9nQcZMtCw0WF3yJYqxaG6R6Mqxq0vRWKEl+PrPBrn+XTHrtr/b+wsk6FOllQlLAvgACrTNVZ3a1Ws8oiu9/e2TvUPq232mhY58NO/z+Pw63ccvK3Cj8n+SR3mPuM85y1QyOi/xLruh1A1J+6Fki5Vk+VgEbQ8aWMhxgN50bL7UcHkVj3AnqOhA8q/aIKFQZ69azWd9JtZy297ZuMVs0uUrwwk3NthbW68s6iZtA+YCMxkB01E8wVVk8LkYH70pEKEs05LfayDrmtOEE3MToapn8lPe3hwns0mQPgDliM8qb/u+/yiLN8V3OKx0qnHQCl1WxhG30e/P6k4mGd6unLa+OvJ2G1+006Bfbq5WQ3i2BESMRskgljnOBCsvhVqjISUtecPdm6XAO3yzzSVNTthgvAVXuH8rti6d0XPAw50ELi4RcC+dIGRChr2ozEZnA2F47MWAdKhTJsOq2wN87FBF6nCd0ITlqAaZ3l3HAgWj3rvXNIt8ctn0oktINYYY1q+4rht1nXPvX1+waBzXZ02lXPkWiGqPUqB1aDAcY+2UBdoEJKm+j94j5QxRvvsdhKx9awzL/HSbXzx5uHtqpXIaNk7T/PjncQ61dnkG+L8=
  - secure: uMVk/uy8bdn6W0SGNVLtsqYFVc95qddviafVBLf9fOHQ2e2Yg+kF+tQ5PV8B7ZKjN7JmIY9lePwW1U/J5kvHt1tAMHaH6pPGF60QacnKVbqiQghm+0gNebw4iR7ev0ATNgTS3F4K3GxCSHUa6GOVsqr1OaHN9dFDK1DlPJvDj9WQDHJuStBIDdRavF7v6hFVSPRYpmyprWgc0L6wFZge/CIluBsNhtGSbxLxghWeY7j11FYKqcn10Mpm9MsFSQcf8kxIc6B2UWeTw/cWpLLsqBaalxcwG7nLfNd1v0+mEeP1cCVETR4Q+psMxBa5dezQr0LdwvzMYNbXvsGS61yLovOaEz0R4vMGaEhRb8uvDYsUxFbqAkFIUMw5KDm1hszco03z6PBdR3y11PAeHOM700+u6oJJOiHfGaSJEbbUOnjp58OdY0nauKuf1w7dLERshVCgBQe4kMJ5XSVhQRD87cBYbRIHv9TRcf5+059feS7KvYPBOfvd+FZ5i7K4UstIGV3rTjzgtTxeLT8u9VWv0FnVs36qAzYGj1rr34QGgHg/luy7d5qovIBo8Bdq4E/BCIB4tHrc0Hx336YT+r5iWGzEu0p5YYgc31yAnn/y4esrMw/ivAIjq5zg9GsNJowm49Hlll3zgMrH9J6A1CBTGadG4HWMexTKciAHyyOH9N0=
  - secure: nzIyCrbZ+vo1AJ3xmuzCizibnFqdDd+JfAsZmUdhWL6M0uENG8z8ZF0NXhXn78FuGko5rJGFHWQrSNyXEqdYOpPebYAI263pSqZaCz14YsscM6B5MHh0Pb0Bs8ADR1/ScNUSHrZMAYdpZhoMWTnpdHWGl8Uig8Rl0ba2DhNL3/X6GD36xLNsOeuhAOjmF71WVMrPFYqYuBOn38IP3nCWA17+08iRGamV89UvPzEN0ee71CqNwtfSF/AeVrQh2fCmJJyQwK8jAxU4QF20e0Q7AMQtlIBVUgdPdzoZFD2b0qX63wOHbhz3qRT342bauVnvGpcqmJXWkARvsYR3ui8OW/UAnMlYlzwIVwnj8QbWSmIa8xk6MoG6OSByL4kDhWCQ6iBHq4OellrZpPDchV0pM77ciFf1qwCNYdeMeJj0KfsIJ0kQenKqKOW0klUE4rgZGNxFgRpgypd71gh6bfdmHjlu7TjEMn88JLMNLoCDMeRsMUBS3XBCvreh0jpgKBye8uqCwlVyZLJsPMsMPWTOTaVcdA9YTC5c2Qhf/Ja6RZqLA27Iu6q4PRJnb+jdpK0v6HUMRuKI9drnb6pXXSlvquzRgteZGpvI2tVrq5s/m0JuAWsCKS5LoK4tMUssDMVIZ5Gzfr2P+TaTgVpM6D2rdpaybuMYgrI/Qiiwsg9/EXA=
before_install:
- openssl aes-256-cbc -K $encrypted_rivage_key -iv $encrypted_rivage_iv -in Rivage.jks.enc -out Rivage.jks -d
script:
- "./gradlew assembleRelease"
before_deploy:
- mv app/build/outputs/apk/release/app-release.apk app/build/outputs/apk/release/Leanote.apk
deploy:
  provider: releases
  api_key:
    secure: iaJM6x+oHFQxbO9Hz7S5uQT10BvoGf2N0n9RnOc/L18npQJW2ndfEnkrI1NtTFcgPwEpOvIG1MT1FdCDa3iwRa6622Aezq2lZswKKATpPcZnWLCiYBexbnMhUyOWzs5gRdTFTrugeU1XtAjaqyiAsgnNF+RJVZT5AtRFb77Ps+ERyOpYoWQAPgouiW7jmbLLuGaGujwjSo303cLMH2UfcELrvgH3rhuAQyKtAXBS22gULuptqDNe7S3GHJAbZ0kWHaDCUqXbueOXE3gIRry+oT7AgTzFZuN2Tp6DHCmodDlWaE9pOhlNblcKCbD5QQWfk90X3yaaJ5X4HlnpeekInqcao7jzVBIeoz66rFWDVL84IfCOLyAPfNuoi69E1CHHUnehWTZEvzEYLlf+I8AZELyeq8lJeS1bS0ExUb24fV1ThYeFIsk+5R633Keu8Gkx3tQDc47osa3fwgMlAyZUh8kgkl7aDdBgahc7NEXxri5nOrVKWAR2Slh+jNrjXCnz42V7ghe7u2lIIDMW0v4KjfnjZrogdTlr0X+RzK/9fjaU3WUZ4tX7x5gp7I7ouWpAoLr3Tj2Imr9vAwljv+RgTmIJToaP5bmry6F/c/HbnPo7XfnXynlG4V/2p01d/+GeQZtjSPFiQu+2QkBKcceLOX61DXjTtWkT+OjVdClBkfE=
  file: app/build/outputs/apk/release/Leanote.apk
  skip_cleanup: true
  on:
    repo: shunf4/leanote-android
    tags: true